### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hugoboos** [voxpupuli/puppet-gitlab_ci_runner#113]
The last release nearly a year ago. Are you willing to release a new version. Because of this we can't update to the latest stdlib.

Thanks!

**Comment by alexjfisher** [comment]
Yes!  It's on my list of things to do this week.  There have been significant changes recently, so It'll be a new major version.  Have you had chance to test the latest version from the master branch?

**Comment by hugoboos** [comment]
No not yet. Will do this.

**Comment by hugoboos** [comment]
It's working. We need to rewrite to config logic, because how the registration is done. Also we need a migration of the registration token. All the runners would re-register them selfs because of the `auth-token-` file solution.

Besides that no other breaking changes.

**Comment by alexjfisher** [comment]
Version 4.0.0 was released in https://github.com/voxpupuli/puppet-gitlab_ci_runner/pull/119
