### ISSUE TITLE
Gitlab runner failed to register: Forbidden

### ISSUE THREAD

**Issue by chrisongthb** [voxpupuli/puppet-gitlab_ci_runner#125]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.24.0
- Ruby: ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
- Distribution: Ubuntu 20.04.3 LTS
- Module version: v4.0.0

## How to reproduce (e.g Puppet code you use)
```ruby
contain ::gitlab_ci_runner
```
```yaml
---
gitlab_ci_runner::concurrent: 4

gitlab_ci_runner::runner_defaults:
  url: 'https://...'
  registration-token: '...'
  executor: 'docker'
  docker:
    image: 'ubuntu:focal'
  builds_dir: '/tmp'
  cache_dir: '/tmp'

gitlab_ci_runner::runners:
  my_test_repo:
    registration-token: '...'
```

## What are you seeing
```console
# puppet agent -t
Info: Using configured environment '...'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Failed to apply catalog: Gitlab runner failed to register: Forbidden
```

## What behaviour did you expect instead
```
Notice: Applied catalog in XX.xx seconds
```

## Output log
```console
# puppet agent -t --debug
[...]
Debug: Caching connection for https://compiler:port
Error: Failed to apply catalog: Gitlab runner failed to register: Forbidden
Debug: Resolving service 'report' using Puppet::HTTP::...
[...]
```

## Any additional information you'd like to impart
* There is no additional debug output printed when using `puppet agent -t --debug` or `puppet agent -t --http_debug`
* The interactive `gitlab-runner register` command succeds (same URI and token as in hieradata)

**Comment by alexjfisher** [comment]
@bastelfreak Do I recall you saying you'd experienced the same in your environment?

**Comment by bastelfreak** [comment]
I had a similar issue, I might be able to gather some logs in the next days when I'm in that specific environment again. @chrisongthb when you do a `--debug` run you sould see the `gitlab-runner register` call, can you paste that?

**Comment by chrisongthb** [comment]
@bastelfreak unfortunately I cannot see any additional debug logs, when I run the agent with `--debug`. The lines in "Output log" above are all I get from `--debug`.

**Comment by chrisongthb** [comment]
After adding some debug statements in `lib/puppet_x/gitlab/runner.rb` I realized, that the registration-token in the hieradata was simply wrong. I must have clicked "reset registration token" too often :woozy_face: 
Sorry for the noise :grimacing:

**Comment by alexjfisher** [comment]
@chrisongthb No worries.  That's good news!

@bastelfreak What's your excuse? ;)
