### ISSUE TITLE
Get acceptance tests setup and running

### ISSUE THREAD

**Issue by LongLiveCHIEF** [voxpupuli/puppet-gitlab_ci_runner#20]
Since the current content of this module was mostly, but not _entirely_ ported over from https://github.com/voxpupuli/puppet-gitlab, it's never actually been installed or run anywhere.

This is a good opportunity to with a fresh start to set up working acceptance tests to ensure the module works as expected with the `v1.0` release.

**Comment by baurmatt** [comment]
Added acceptance tests in https://github.com/voxpupuli/puppet-gitlab_ci_runner/issues/20. Hope that's enough :)

**Comment by baurmatt** [comment]
I've meant #74 🙈
