### ISSUE TITLE
Gitlab 18+

### ISSUE THREAD

**Issue by rogermartensson** [voxpupuli/puppet-gitlab_ci_runner#208]
Gitlab 18 and forward are planning to make some changes in the Gitlab runner.

Do this module going to be affected with these changes?

**Comment by yakatz** [comment]
I am working on the new runner registration workflow which is already an issue, but I don't know of any major issues related to 18.

**Comment by rogermartensson** [comment]
Thank you for your answer and your work. I guess we will wait and see. Version 18 is still some way off before releasing.
