### ISSUE TITLE
Forge Release

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-gitlab_ci_runner#24]
Hi!

since the module puppet/gitlab released 3.0.0 without runner management this module should be released to cover the missing functionality.

**Comment by mungo312** [comment]
Any news ?

**Comment by alexjfisher** [comment]
Would someone like to create a release PR?

**Comment by alexjfisher** [comment]
I’d recommend a release 1.0.0 summary issue too that can be used as content in the changelog.

**Comment by alexjfisher** [comment]
@jkroepke is there anything else you can think of for the first release?

Off the top of my head...
README updates (who doesn’t like badges)
REFERENCE.MD ?

**Comment by alexjfisher** [comment]
https://forge.puppet.com/puppet/gitlab_ci_runner

Released thanks to @baurmatt!
