### ISSUE TITLE
The package `xz-utils` is `xz` on CentOS

### ISSUE THREAD

**Issue by ajcollett** [voxpupuli/puppet-gitlab_ci_runner#25]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Ruby:
- Distribution: CentOS
- Module version: git master

## How to reproduce (e.g Puppet code you use)
Use with a CentOS host.

## What are you seeing
The package `xz-utils` is `xz` on CentOS. This needs to be set manually for CentOS installs it seems.

## What behaviour did you expect instead
Module should use `xz` or `xz-utils` based on the OS, rather than this needing to be set manually. 

## Output log
Let me know if you need this. 

## Any additional information you'd like to impart
This was probably going to be done at some point, but this should help track it.

**Comment by LongLiveCHIEF** [comment]
What version of CentOS are you using? (and is it CentOS or RHEL?) 

I _think_ this dependency is no longer required. but not positive. If so, we should make sure acceptance tests accurately fail this.

If it _is_ required by the package, then I believe it's only required if you're installing the runner package and using the shell executor.  

I think we need to work through these scenarios and figure out what's accurate, then add the appropriate tests, and finally set up hiera data accordingly so the right packages are installed for the right OS's.

**Comment by m-shaffer** [comment]
I'm seeing this on Red Hat Enterprise Linux Server release 7.6. I agree that it doesn't appear to be impacting any functionality.

**Comment by smortex** [comment]
Seeing this on CentOS 7 too.  Will submit a PR.
