### ISSUE TITLE
Metrics server and Session listen address'

### ISSUE THREAD

**Issue by ajcollett** [voxpupuli/puppet-gitlab_ci_runner#26]
## Gitlab Runner Metrics server option rename
`metrics_server` is being depreciated, and will be replaced with the `listen_address` option. 

See here: https://docs.gitlab.com/runner/monitoring/#configuration-of-the-metrics-http-server

## GitLab `session_server` config
The `session_server` section should be configurable through the module. I need to fully investigate if this has been implemented but it seems not from a cursory look over the code. 
Here is a link to the config section in the GitLab docs: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-session_server-section

**Comment by ajcollett** [comment]
Actually, after my last merge request, I realise most of the options are just the command line options, so this is then irrelevant?

**Comment by LongLiveCHIEF** [comment]
> I realise most of the options are just the command line options, so this is then irrelevant

@ajcollett the command line options write out to a static confilg file (`config.toml`) for runner restarts/upgrades.  So yeah, I think this is still a valid issue.

The trick is going to be indicating what versions of the gitlab runner this module is compatible with.  (Similar to the [module support](https://github.com/voxpupuli/puppet-gitlab/pull/294) info we recently added to the `puppet/gitlab` module. )
