### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jacksgt** [voxpupuli/puppet-gitlab_ci_runner#58]
Hi,

this module has not seen a new release for a year now, despite the fact that there have been quite a few updates and fixes since then:

https://github.com/voxpupuli/puppet-gitlab_ci_runner/compare/v1.0.0...master

Thank you for maintaining this module.

**Comment by alexjfisher** [comment]
@baurmatt You're probably best placed to know if there's anything else needing finishing off before a new release.  In particular though, could you look at some of the comments left on https://github.com/voxpupuli/puppet-gitlab_ci_runner/pull/74?

**Comment by baurmatt** [comment]
Hey @alexjfisher and @jacksgt, I'm planing trigger a release after fixing what @Farfaday found in #74. In particular I want to get a release before #75 gets merged because of the breaking change regarding the runner registration.
