### ISSUE TITLE
registration_token containing undescore gets modified

### ISSUE THREAD

**Issue by Farfaday** [voxpupuli/puppet-gitlab_ci_runner#61]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.10.1
- Ruby:
- Distribution: ubuntu bionic
- Module version: current master (18.11.2019)

## How to reproduce (e.g Puppet code you use)
If the registration_token contains an underscore, it gets converted into a "minus", and then of course the registration fails

## What behaviour did you expect instead
Should be able to register :)

**Comment by jacksgt** [comment]
Also reported in https://github.com/voxpupuli/puppet-gitlab_ci_runner/issues/45#issuecomment-502840331

**Comment by Farfaday** [comment]
Fixed via https://github.com/voxpupuli/puppet-gitlab_ci_runner/pull/74
