### ISSUE TITLE
How to add sysctls value

### ISSUE THREAD

**Issue by accessone67** [voxpupuli/puppet-gitlab_ci_runner#96]
Can some1 point me out how can I add sysctls with hiera. I have tryed many ways and always fails. I cant figure out the right syntax. 

if I put like this
["vm.swappiness=0","vm.overcommit_memory=1"] in the config it apears
"vm.swappiness=0" = ""
"vm.overcommit_memory=1" = ""

or:
docker-sysctls:
  vm.swappiness: 0
will make this registration parameter and fails.
--docker-sysctls={vm.swappiness => 0} --registration-token

any help would be greatly appreciated

**Comment by kenyon** [comment]
Use one of the sysctl modules: https://forge.puppet.com/modules?q=sysctl

I don't see how this is relevant to this repository, therefore closing this issue.
